name: Parse-SVNDiff
version: 0.01
abstract: Subversion binary diff format parser
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  perl: 5.8.0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
